### ISSUE TITLE
Transform Variable doesn't work for same variable

### ISSUE THREAD

**Issue by SDxKeeper** [jessehouwing/vsts-variable-tasks#11] opened 2016-05-19 17:23 UTC
I have sequence of 2 tasks:
1. Expand Variable $(ChangeSet) which is set to $(Build.SourceVersion) by default on variables tab
2. Transform Variable task which strips leading C from Source version of TFVC (reproducible only on On-Premises TFS2015 U2): Input variable $(ChangeSet), output variable ChangeSet
In the log I see that value was correctly set
But later steps still use value of the $(ChangeSet) is still like it was not gone through step 2. (with leading "C" in my example)

Am I the only one who face this issue with transform variable task for same input/output?

**Comment by jessehouwing** [comment] 2016-05-19 17:34
What build agent version are you using?

**Comment by jessehouwing** [comment] 2016-05-19 18:30
When I'm testing against the agent version that ships with TFS 2015u2, I get a warning that the task isn't supported on this agent version. When I then install the VSTS agent and configure it against TFS2015u2 the task works as expected.

Can you turn on `System.Debug`=`true` in the build definition's variables section and post the logs here as an attachment to the issue?

**Comment by jessehouwing** [comment] 2016-05-19 19:05
Looks like a bug in the agent. I've been able to repro this in multiple ways. Not using expand variable (it is no longer needed with the latest VSTS agent) and relying on SetVariable allows you to work around this.

**Comment by SDxKeeper** [comment] 2016-05-19 19:07
Thank you for quick response! I'll try to update to VSTS agent tomorrow.

**Comment by SDxKeeper** [comment] 2016-05-23 11:26
Issue is reproducible with latest VSTS agent version 1.99.0. Rolled back to workaround usage: SetVariable to a different variable name.

**Comment by jessehouwing** [comment] 2016-05-25 19:47
What tasks (the later steps you mention) have issues reading the variable? I'm working with Microsoft to see what the impact is. It's been confirmed as a bug in the current Windows agent and has been resolved in the upcoming .NET Core based agent, but that won't help you on 2015.

**Comment by SDxKeeper** [comment] 2016-05-25 22:02
Stock "batch script" task for sure and probably "command line" one. Will
post full list tomorrow
25 Май 2016 г. 22:47 пользователь "Jesse Houwing" <notifications@github.com>
написал:

**Comment by jessehouwing** [comment] 2016-05-27 09:06
I received confirmation from Mcirosoft that this is a bug in the Powershell handler that is used by the Variable Transform task. It should be fixed with TFS 2015 update 3.

**Comment by jessehouwing** [comment] 2016-07-03 11:14
closing now Update 3 has been released.

**Closed by jessehouwing** 2016-07-03 11:14 UTC
Labels: bug
